### ISSUE TITLE
Compatibility with extraRole

### ISSUE THREAD

**Issue by Snowad14** [Aeolic/CultistMod#1]
your mod works pretty well but i noticed it didn't work with extrarole, i also learned a lot from this mod, would it be cool if you could make it compatible? Doesn't matter if you can't for lack of time / desire I would try to fork it

**Comment by Aeolic** [comment]
Feel free to fork it and make it compatible, I'd love to see the two mods work together.
I might try to make it compatible eventually, but it would probably make more sense to add the Cultist to the Extra Roles, because if you are running both of them together, I can imagine that there are a lot of conflicting patches...
